### ISSUE TITLE
Data Entry - When a sampler is not yet in the database

### ISSUE THREAD

**Issue by mzperry** [dancrocker/BRCWQDM#17]
This one is for discussion.  All samplers should be in the database prior to an event or, at worst, prior to data entry.  However. in the event they are not, the FC is faced with holding the data entry back, holding the record back, or using a placeholder name.  Is there value in having a fixed placeholder name that would flag the issue without delaying submittal of the data and make it easy to correct?

**Comment by dancrocker** [comment]
Yes, I can add a placeholder name to select - the name can easily be fixed in the database, or during the PC review.  I will add the name  "BRC SamplerX" as a placeholder name, unless there is another option you prefer

**Comment by mzperry** [comment]
"BRC SamplerX" has a nice ring to it.

**Comment by dancrocker** [comment]
BRC SamplerX was added to the list of samplers. This should be used temporarily. The PC will need to add the actual name to the people/assignments tables, update the database files through the app and then fix the record in the database. A comment should be added to the sample event indicating who Sampler X is.
