### ISSUE TITLE
Data Entry

### ISSUE THREAD

**Issue by jtrahanliptak** [dancrocker/BRCWQDM#2]
Chose sample location - might be more useful to include the water body name and location or code.  Should also discuss just numbering the sites sequentially for easier data input.

**Comment by mzperry** [comment]
Agreed.  I think the best approach for now is to use the names I used in the interim entry form since that is what the FCs will be familiar with.  I can either edit the table or supply a from/to list to facilitate this.  Also, BRC code is not needed if location is clear.

**Comment by dancrocker** [comment]
I changed the site selection to: `waterbody name` - `site name` (brc site code).
No, brc code not needed, but this is the primary key for the sites table and its what gets populated in data tables - so good to keep here IMO. Let me know if change is acceptable and I will close issue.
