### ISSUE TITLE
Staged Comments Edit - Commenter field blanks

### ISSUE THREAD

**Issue by mzperry** [dancrocker/BRCWQDM#20]
Sometimes the commenter field blanks after editing location.  Only happened with FC name.  Sometimes but not always the change was real that is Commenter was blank on the Staged Comments page after update.  Editing by using the pulldown replaces the name.  The only name in the pulldown is the original name.   Low priority - just weird.

**Comment by dancrocker** [comment]
I think this has been addressed. Please reopen if it occurs again. I cannot replicate this problem.
