### ISSUE TITLE
Staged Comments - comments associated with incorrect site number

### ISSUE THREAD

**Issue by mzperry** [dancrocker/BRCWQDM#21]
Comments are associated with incorrect site number.  First observed in Submitted Comments after submittal.  Confirmed in Staged Comments backup file.

While entering data, Staged Comments was checked after records containing comments were entered.   5 comments entered with no errors.  All were single comments - one per record.  Error appeared at comment 6.  Comments 6 and 7 were entered associated with the same record but 6 was associated with the previous record's site number.

Comment 8 was entered in the next record but was associated with the same site number as comment 5 and 6.
[BRC_StagedComments - bug.txt](https://github.com/dancrocker/BRCWQDM/files/3790730/BRC_StagedComments.-.bug.txt)

**Comment by mzperry** [comment]
Attached is the final staged comments file from data entry.  Incorrect site numbers are flagged in red and column added for correct site number.
[BRC_StagedComments_flagged.xlsx](https://github.com/dancrocker/BRCWQDM/files/3791050/BRC_StagedComments_flagged.xlsx)

**Comment by dancrocker** [comment]
This issue has been fixed. Created reactive objects for site, date, and sampler so that they could be passed to module would update appropriately when info changed. Tested several times... could use confirmation from coordinators and I will close issue.

**Comment by dancrocker** [comment]
Closing issue - no new reports of this problem
