### ISSUE TITLE
Data Entry/Sample Location - segregate by region?

### ISSUE THREAD

**Issue by mzperry** [dancrocker/BRCWQDM#4]
Is it possible (or desirable) to segregate by region either by CoordinatorZone or user?  Easier on the FC if they only see their own sites.

**Comment by dancrocker** [comment]
Yes, I agree. Does the BRC CODE letter (A,B,C) signify the zone? There needs to be some grouping variable in the sites table so that I can do this. Once I know the grouping variable I can implement this.

**Comment by mzperry** [comment]
Not surprisingly, the answer is yes and no.  I still have no answer on BRC code format but we can infer that the letter indicates the zone.  And it's true right now that the FCs only have sites in their zone with the corresponding letter.  However it was not always the case and there's no guarantee for the future.   I would say that the letter indicates physical location but not administrative location.  I guess we may need to add a variable for this?

**Comment by dancrocker** [comment]
Yes, we need a variable added to the sites table... "ZONE" seems like a logical choice.

**Comment by dancrocker** [comment]
ZONE was added to the sites table. Lower-reach change to Rhode Island?
