### ISSUE TITLE
Data Entry - entry formats

### ISSUE THREAD

**Issue by mzperry** [dancrocker/BRCWQDM#5]
Multiple choice (weather, trash, NAV) are probably better as selection boxes.  Likewise multiple selection lists (appearance, erosion, odor, turb) are definitely better as checkboxes.  Pulldowns are just less efficient for these entry types.  Volunteer name could go either way.  I set it up as a checkbox list on the interim form, limited to the region.  Handy when selecting multiple volunteers at a site as you don't need to repeat the pulldown operation - just scan and check.  Depth method (which I like) could be multiple choice though here the pulldown is not onerous.  Location is definitely a pulldown.

**Comment by dancrocker** [comment]
I can change any inputs to checkbox style easily. I did pull-downs to conserve space, and reduce need for scrolling. For long lists the pull downs are nice because you can type in the box to skip down the list.  Checkboxes for volunteers would fill an entire page. I can change the depth selection to checkbox style easily.

**Comment by mzperry** [comment]
Normally, I'm very anti-scrolling.  However, I'm surprised by how quickly I can enter using the interim form which is essentially one long column - scroll, click.  It's muscle memory.  Also, pointer selection seems faster in the case of multiple selection or correcting a selection.  Having said that, I'm not a typist, more mouse oriented.  Sad really as I started out with emacs and the command line only to be corrupted by GUI.  Others may prefer pull and select or type and select.  Also I'm hampered by not having full screen so I often can't see all the selections without careful positioning.  I might try soliciting the opinion of another FC and Joy? before we commit.

I agree on volunteers, type and select pulldown is probably fastest.  I have it limited to zone on the interim form so the scroll isn't that bad.

**Comment by dancrocker** [comment]
Mulit-select inputs are now checkbox style. Single select inputs are radio buttons (I have no control over this). Please review and see if you like it.
