### ISSUE TITLE
Data Entry/Water Clarity

### ISSUE THREAD

**Issue by mzperry** [dancrocker/BRCWQDM#7]
I note deviations here from the data sheet.   I don't disagree with them but did they come from Susan?  For the interim form she had me distinguish between Visual Turbidity and Lab Turbidity and leave the selections alone.

**Comment by dancrocker** [comment]
They came from me, but I can change the choices back to the datasheet - no problem.

**Comment by mzperry** [comment]
Trying to make us more technically accurate? :-)   The parameter heading may not matter but we probably need to be consistent with historical data on the selections.  If only we were starting from scratch.

**Comment by dancrocker** [comment]
I guess I was, however consistency trumps accuracy in this situation. The change has been made.
