### ISSUE TITLE
Data Entry/Sampler(s) - provision for "other"

### ISSUE THREAD

**Issue by mzperry** [dancrocker/BRCWQDM#8]
If possible, we need the ability to add multiple volunteers not on the list.  While it's simple with the "wild west" we have currently, I have no idea how to to handle this with the constraints of the database.  There's a number of cases where it happens. Some are more transient than others but we like to record them both to acknowledge the contribution and to push up the stats.  It's further complicated by the fact that some may be later entered in the table and some may not (though I suppose this could become a rule that they must be entered or deleted).  This one requires some thought and discussion.

**Comment by dancrocker** [comment]
This is possible to do, but it compromises data integrity - inevitably names will get written manually in different ways. We can discuss this further. Ideally, we would know all people involved in advanced and they can be added to the people table and assignments table.

**Comment by mzperry** [comment]
You convinced me.  A little manual back and forth between the PC and FC can facilitate a table edit fairly quickly and worst case the name could be CAREFULLY added at staging or QC.  I could envision a future simple form and process, kind of a FC volunteer request but a simple DOCUMENTED manual process is more than adequate.
